"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
${custom.directory}\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$shell\
$character
"""

right_format = "$all"

[bun]
symbol = " "
format = ' [$symbol($version)]($style)'

[cmd_duration]
format = ' [\[$duration\]]($style)'

[directory]
disabled = true

[custom.directory]
command = '''
output=$(pwd | sed "s|/Users/$USER|~|" | sed "s|~/Developer/github.com/| |")
echo "$output"
'''
when = true
format = "[$output]($style) "
style = "cyan bold"

[docker_context]
symbol = " "
format = '[$symbol$context]($style)'

[dotnet]
symbol = ".NET "
format = ' [$symbol($version)]($style)'

[git_branch]
symbol = " "
format = '[$symbol$branch]($style)'

[git_commit]
tag_symbol = '  '

[git_status]
format = ' ([\($all_status$ahead_behind\)]($style))'

[hostname]
ssh_symbol = " "

[nodejs]
symbol = " "
format = ' [$symbol($version)]($style)'
detect_files = [ "package.json", "!bun.lockb" ]

[os]
format = '[$symbol]($style)'

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
format = '[$symbol$version]($style)'

[sudo]
format = '[as $symbol]($style)'

[time]
disabled = false
time_format = "%R"
format = ' [\[$time\]]($style)'
style = "dimmed"

[username]
format = '\[[$user]($style)\]'
